[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nftstaking_program = "E6vWq2ax8LG1hVShtFR3hNKAmZFAYVmeokwseAfi63ic"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\samue\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
